product:
  backend:
    url: http://localhost:8080
payment:
  backend:
    url: http://localhost:9000
delivery:
  backend:
    url: http://localhost:9090
server:
  port: 8090
spring:
  thymeleaf:
    cache: false
