spring:
  application:
    name: deliver-service
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_db
    username: root
    password: kyaw549235
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9090
